# Generated by Django 4.2.4 on 2023-09-04 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'AthleteProfile',
            },
        ),
        migrations.CreateModel(
            name='AthleteQuestionTest',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='TimeStamp')),
                ('athlete_profile', models.ForeignKey(db_column='AthleteProfileID', on_delete=django.db.models.deletion.CASCADE, to='API_Authentication.athleteprofile')),
            ],
            options={
                'db_table': 'AthleteQuestionTest',
            },
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('connection_type', models.CharField(db_column='ConnectionType', max_length=255)),
            ],
            options={
                'db_table': 'ConnectionType',
            },
        ),
        migrations.CreateModel(
            name='PersonQuestion',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('question', models.CharField(db_column='Question', max_length=1000)),
                ('weight', models.PositiveIntegerField(db_column='Weight', default=0)),
            ],
            options={
                'db_table': 'PersonQuestions',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'Sports',
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('biography', models.CharField(blank=True, db_column='Biography', max_length=1000)),
                ('certificate', models.ImageField(blank=True, db_column='Certificate', max_length=1000, upload_to='API_Authentication/user/certificate/')),
                ('is_available_online', models.BooleanField(db_column='IsAvailableOnline', default=False)),
                ('is_dietician', models.BooleanField(db_column='IsDietician', default=False)),
                ('price_per_hour', models.PositiveIntegerField(db_column='PricePerHour', default=0)),
            ],
            options={
                'db_table': 'TrainerProfile',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('birth_date', models.DateField(db_column='BirthDate', null=True)),
                ('email', models.EmailField(db_column='Email', max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=255)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=255)),
                ('profile_picture', models.ImageField(blank=True, db_column='ProfilePicture', max_length=1000, upload_to='API_Authentication/user/image/')),
                ('sex', models.BooleanField(db_column='Sex (1 stands for male)', null=True)),
                ('is_admin', models.BooleanField(db_column='IsAdmin', default=False)),
                ('athlete_profile', models.ForeignKey(db_column='AthleteProfileID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_Authentication.athleteprofile')),
                ('trainer_profile', models.ForeignKey(db_column='TrainerProfileID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_Authentication.trainerprofile')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserSport',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sport', models.ForeignKey(db_column='SportID', on_delete=django.db.models.deletion.CASCADE, to='API_Authentication.sport')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserSports',
            },
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('connection_type', models.ForeignKey(db_column='ConnectionTypeID', on_delete=django.db.models.deletion.CASCADE, to='API_Authentication.connectiontype')),
                ('user1', models.ForeignKey(db_column='User1ID', on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(db_column='User2ID', on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserConnections',
            },
        ),
        migrations.CreateModel(
            name='TrainerRating',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(db_column='Rating', default=0)),
                ('athlete_profile', models.ForeignKey(db_column='AthleteProfileID', on_delete=django.db.models.deletion.CASCADE, to='API_Authentication.athleteprofile')),
                ('trainer_profile', models.ForeignKey(db_column='TrainerProfileID', on_delete=django.db.models.deletion.CASCADE, to='API_Authentication.trainerprofile')),
            ],
            options={
                'db_table': 'TrainerRatings',
            },
        ),
        migrations.CreateModel(
            name='PersonQuestionWeighing',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('weight', models.PositiveIntegerField(db_column='Weight', default=0)),
                ('athlete_question_test', models.ForeignKey(db_column='AthleteQuestionTestID', on_delete=django.db.models.deletion.CASCADE, to='API_Authentication.athletequestiontest')),
                ('person_question', models.ForeignKey(db_column='PersonQuestionID', on_delete=django.db.models.deletion.CASCADE, to='API_Authentication.personquestion')),
            ],
            options={
                'db_table': 'PersonQuestionWeighings',
            },
        ),
    ]
