# Generated by Django 4.2.4 on 2023-09-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='biography',
            field=models.CharField(blank=True, db_column='Biography', max_length=1000),
        ),
    ]
