# Generated by Django 4.2.4 on 2023-10-06 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Authentication', '0003_userathleteconnection_usertrainerconnection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personquestionweighing',
            name='athlete_question_test',
        ),
        migrations.AddField(
            model_name='personquestionweighing',
            name='athlete_profile',
            field=models.ForeignKey(db_column='AthleteProfileID', default=1, on_delete=django.db.models.deletion.CASCADE, to='API_Authentication.athleteprofile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AthleteQuestionTest',
        ),
    ]
