# Generated by Django 4.2.4 on 2023-10-28 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Authentication', '0004_remove_personquestionweighing_athlete_question_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='athlete_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trainer_profile',
        ),
        migrations.RemoveField(
            model_name='userathleteconnection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertrainerconnection',
            name='user',
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='user',
            field=models.OneToOneField(db_column='User', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(db_column='User', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userathleteconnection',
            name='athlete_profile_liked',
            field=models.ForeignKey(db_column='AthleteProfileLiked', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile_liked', to='API_Authentication.athleteprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertrainerconnection',
            name='athlete_profile',
            field=models.ForeignKey(db_column='AthleteProfile', default=1, on_delete=django.db.models.deletion.CASCADE, to='API_Authentication.athleteprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userathleteconnection',
            name='athlete_profile',
            field=models.ForeignKey(db_column='AthleteProfile', on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to='API_Authentication.athleteprofile'),
        ),
    ]
