# Generated by Django 4.2.4 on 2023-11-04 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Authentication', '0005_remove_user_athlete_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAthleteConnection',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('connect', models.BooleanField(db_column='Connect')),
                ('athlete_profile', models.ForeignKey(db_column='AthleteProfile', on_delete=django.db.models.deletion.CASCADE, to='API_Authentication.athleteprofile')),
                ('trainer_profile', models.ForeignKey(db_column='TrainerProfile', on_delete=django.db.models.deletion.CASCADE, to='API_Authentication.trainerprofile')),
            ],
            options={
                'db_table': 'TrainerAthleteConnections',
            },
        ),
    ]
