# Generated by Django 4.2.4 on 2023-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Authentication', '0006_trainerathleteconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='height',
            field=models.PositiveIntegerField(db_column='Height', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='weight',
            field=models.PositiveIntegerField(db_column='Weight', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, db_column='City', max_length=100),
        ),
    ]
