# Generated by Django 4.2.4 on 2023-11-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Authentication', '0007_athleteprofile_height_athleteprofile_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_contact',
            field=models.CharField(db_column='FacebookContact', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_contact',
            field=models.CharField(db_column='InstagramContact', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_contact',
            field=models.CharField(db_column='LinkedinContact', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='other_contact',
            field=models.CharField(db_column='OtherContact', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_column='Phone', max_length=25, null=True),
        ),
    ]
